# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ticket_background', models.ImageField(blank=True, upload_to='', verbose_name="Fond d'image tickets")),
                ('sales_opening', models.DateTimeField(default=datetime.datetime.now)),
                ('sales_closing', models.DateTimeField(default=datetime.datetime.now)),
                ('max_seats', models.IntegerField(default=1600, verbose_name='Nombre maximal de place')),
                ('seats_goal', models.IntegerField(default=1600)),
                ('logo_url', models.CharField(blank=True, default='http://logos.bde-insa-lyon.fr/bal/Logo_bal.png', max_length=2500, null=True)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'verbose_name': 'Evènement',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('link_sent', models.BooleanField()),
                ('reason', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix TTC')),
                ('max_seats', models.IntegerField(default=1600, verbose_name='Nombre maximal de place')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event', verbose_name='Evènement')),
            ],
            options={
                'verbose_name': 'Tarification',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Billet')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentProtocol', models.CharField(choices=[('CB', 'payment by Credit Card'), ('ESP', 'payment by cash'), ('VIR', 'payment by bank transfer')], max_length=50)),
                ('paymentMin', models.IntegerField(default=-1000000)),
                ('paymentMax', models.IntegerField(default=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BYI', 'Limit by product by invitation'), ('BYTI', 'Limit by total product by invitation'), ('T', 'Global gap of product'), ('VA', 'Require VA validation (not implemented)')], max_length=50)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix TTC')),
                ('max_seats', models.IntegerField(default=1600, verbose_name='Nombre maximal de place')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event', verbose_name='Evènement')),
                ('pricings', models.ManyToManyField(to='api.PricingRule')),
            ],
            options={
                'verbose_name': 'Tarification',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('help_text', models.TextField()),
                ('question_type', models.IntegerField(verbose_name='type de question')),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='questions',
            field=models.ManyToManyField(to='api.Question'),
        ),
        migrations.AddField(
            model_name='option',
            name='pricings',
            field=models.ManyToManyField(to='api.PricingRule'),
        ),
        migrations.AddField(
            model_name='option',
            name='products',
            field=models.ManyToManyField(related_name='options', to='api.Product'),
        ),
        migrations.AddField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(to='api.Question'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.AddField(
            model_name='billet',
            name='options',
            field=models.ManyToManyField(related_name='billets', to='api.Option'),
        ),
        migrations.AddField(
            model_name='billet',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='api.Product'),
        ),
    ]
