# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billetoption',
            options={'verbose_name': 'lien entre une option et un billet'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'commande'},
        ),
        migrations.RemoveField(
            model_name='billetoption',
            name='order',
        ),
    ]
