# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billets', models.ManyToManyField(blank=True, to='api.Billet')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': "Tarif d'option"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tarif de billet'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='option',
            name='pricings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_seats',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pricings',
        ),
        migrations.AddField(
            model_name='option',
            name='rules',
            field=models.ManyToManyField(blank=True, to='api.PricingRule'),
        ),
        migrations.AddField(
            model_name='product',
            name='rules',
            field=models.ManyToManyField(blank=True, to='api.PricingRule'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.Question'),
        ),
        migrations.AlterField(
            model_name='product',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.Question'),
        ),
    ]
