# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0006_auto_20171126_1823'),
        ('api', '0002_lien_billet_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercanet.TransactionRequest'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pas initialisée'), (1, 'Sélection des produits'), (3, 'Sélection des options'), (5, 'Paiement'), (6, 'Confirmée'), (4, 'Commande en cours de confirmation par le client'), (2, 'Sélection des participants')], default=0, verbose_name='status'),
        ),
    ]
