# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171126_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Champ libre'), (1, 'Champ libre (long)'), (2, 'Choix multiple'), (3, 'Choix multiple et libre'), (4, 'Choix'), (5, 'Date'), (6, 'Date et heure'), (7, 'Heure')], verbose_name='type de question'),
        ),
    ]
