# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171113_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
