# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171113_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Tarif des option'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Organisateur'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Moyens de paiement'},
        ),
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'verbose_name': 'Règles de poduits (Jauges/Limite'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tarif des produit'},
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Nom du lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Adresse du lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name="Fin de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_url',
            field=models.CharField(blank=True, default='http://logos.bde-insa-lyon.fr/bal/Logo_bal.png', max_length=2500, null=True, verbose_name='Url du logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='sales_closing',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Clôture des ventes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sales_opening',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ouverture des ventes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats_goal',
            field=models.IntegerField(default=1600, verbose_name='Nombre de place visé'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name="Début de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Site Web'),
        ),
    ]
