# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171129_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
