# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171116_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Categorie', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Categorie', verbose_name='Catégorie'),
        ),
    ]
