# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('single', 'Unique'), ('multiple', 'Plusieurs')], default='single', max_length=30),
            preserve_default=False,
        ),
    ]
