# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_option_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('permission_level', models.IntegerField(choices=[(0, 'Administrateur'), (100, 'Gestionnaire'), (1000, 'Lecture seul')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Organizer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='api.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
