# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171130_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='events',
            field=models.ManyToManyField(blank=True, to='api.Event'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Organizer'),
        ),
    ]
