# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:50
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171125_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='products',
        ),
        migrations.AddField(
            model_name='invitation',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=api.models.generate_token, max_length=32),
        ),
        migrations.AddField(
            model_name='option',
            name='target',
            field=models.CharField(choices=[('Order', 'Globalement sur la commande'), ('Billet', 'Pour chaque billet'), ('Participant', 'Pour chaque participant')], default='Participant', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.CharField(choices=[('Order', 'Globalement sur la commande'), ('Billet', 'Pour chaque billet'), ('Participant', 'Pour chaque participant')], default='Participant', max_length=30),
        ),
    ]
