# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171204_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='link_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
