# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171205_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
