# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171125_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.Client'),
        ),
    ]
