# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_compostage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='product_type',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
    ]
