# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171125_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilletOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='billet',
            name='options',
        ),
        migrations.AddField(
            model_name='billetoption',
            name='billet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Billet'),
        ),
        migrations.AddField(
            model_name='billetoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Option'),
        ),
    ]
