# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171214_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='validation_type',
            field=models.IntegerField(choices=[(0, 'Aucun mode défini'), (1, 'Validation de produits'), (2, "Validation d'options")], default=0),
        ),
    ]
