# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171125_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='options',
            field=models.ManyToManyField(related_name='billets', through='api.BilletOption', to='api.Option'),
        ),
    ]
