# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_billet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetoption',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options_by_billet', to='api.Participant'),
        ),
    ]
