# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_billetoption_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetoption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billet_options', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='billetoption',
            name='billet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billet_options', to='api.Billet'),
        ),
    ]
