# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def drop_billets(*__, **_):
    from api.models import Billet
    Billet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171125_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billets',
        ),
        migrations.AddField(
            model_name='billet',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
        migrations.RunPython(drop_billets),
        migrations.AlterField(
            model_name='billet',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
