# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import mercanet.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmercanet',
            name='serverToken',
            field=models.CharField(default=mercanet.models.generate_token, max_length=127, verbose_name="clef d'identification du serveur Mercanet"),
        ),
    ]
