# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0002_transactionmercanet_servertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmercanet',
            name='serverToken',
        ),
    ]
