# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0002_remove_transactionmercanet_responsetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmercanet',
            name='responseText',
            field=models.CharField(blank=True, max_length=256, verbose_name='Status de la transaction'),
        ),
    ]
