# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import mercanet.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0003_remove_transactionmercanet_servertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercanetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverToken', models.CharField(default=mercanet.models.generate_token, max_length=127, verbose_name="clef d'identification du serveur Mercanet")),
                ('transactionReference', models.CharField(max_length=35, verbose_name='UUID (Référence MercaNET)')),
            ],
            options={
                'verbose_name': 'identification de MercaNET aurpès de billevent',
            },
        ),
    ]
