# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0003_transactionmercanet_responsetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name="montant en centimes d'euros")),
                ('callback', models.CharField(max_length=2000, verbose_name='url de retour client')),
                ('started', models.BooleanField(verbose_name='pris en charge par mercanet')),
                ('mercanet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercanet.TransactionMercanet')),
            ],
        ),
    ]
