# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import mercanet.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0004_transactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='token',
            field=models.CharField(default=mercanet.models.generate_token, max_length=127, verbose_name="clef d'accès"),
        ),
    ]
