# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0004_mercanettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercanettoken',
            options={'verbose_name_plural': 'identification de Mercanet auprès de billevent'},
        ),
        migrations.AddField(
            model_name='mercanettoken',
            name='mercanet2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercanet.TransactionMercanet'),
        ),
    ]
