# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0005_auto_20171126_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmercanet',
            name='responseCode',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='(responseCode)VERIF PAIEMENT SI=0'),
        ),
    ]
