# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0004_auto_20171126_0218'),
        ('mercanet', '0005_transactionrequest_token'),
    ]

    operations = [
    ]
