# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0006_auto_20171126_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrequest',
            name='mercanet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='mercanet.TransactionMercanet'),
        ),
    ]
