# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercanet', '0007_auto_20171127_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmercanet',
            name='sealCheck',
            field=models.NullBooleanField(verbose_name='seal autoMercanet valide'),
        ),
    ]
